services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - rmq
    ports:
      - '80:80'
  rmq:
    image: rabbitmq:4-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

